import { addIcon } from "@iconify/vue/dist/offline";

/**
 * 这里存放本地图标，在 src/layout/index.vue 文件中加载，避免在首启动加载
 */

// 本地菜单图标，后端在路由的icon中返回对应的图标字符串并且前端在此处使用addIcon添加即可渲染菜单图标
import Check from "@iconify-icons/ep/check";
import HomeFilled from "@iconify-icons/ep/home-filled";
import Lollipop from "@iconify-icons/ep/lollipop";
import RefreshRight from "@iconify-icons/ep/refresh-right";
import Close from "@iconify-icons/ep/close";
import CloseBold from "@iconify-icons/ep/close-bold";
import Bell from "@iconify-icons/ep/bell";
import Search from "@iconify-icons/ep/search";
import Refresh from "@iconify-icons/ep/refresh";
import InfoFilled from "@iconify-icons/ep/info-filled";
import Collection from "@iconify-icons/ep/collection";
import Download from "@iconify-icons/ep/download";
import TrendCharts from "@iconify-icons/ep/trend-charts";
import Position from "@iconify-icons/ep/position";
import Location from "@iconify-icons/ep/location";
import MapLocation from "@iconify-icons/ep/map-location";
import Iphone from "@iconify-icons/ep/Iphone";
import Tickets from "@iconify-icons/ep/Tickets";
import Postcard from "@iconify-icons/ep/Postcard";
import Female from "@iconify-icons/ep/Female";
import Connection from "@iconify-icons/ep/Connection";
import Calendar from "@iconify-icons/ep/calendar";
import Medal from "@iconify-icons/ep/medal";
import Link from "@iconify-icons/ep/Link";
import House from "@iconify-icons/ep/House";
import UserEM from "@iconify-icons/ep/User";
import Present from "@iconify-icons/ep/present";
import Warning from "@iconify-icons/ep/warning";
import Delete from "@iconify-icons/ep/delete";
import DownLoad from "@iconify-icons/ep/download";
import Upload from "@iconify-icons/ep/upload";
import EditPen from "@iconify-icons/ep/edit-pen";
import DataAnalysis from "@iconify-icons/ep/data-analysis";
import Money from "@iconify-icons/ep/money";
import Coin from "@iconify-icons/ep/coin";
import Operation from "@iconify-icons/ep/operation";
import OfficeBuilding from "@iconify-icons/ep/office-building";
import Lock from "@iconify-icons/ep/lock";
import CreditCard from "@iconify-icons/ep/credit-card";
import Guide from "@iconify-icons/ep/guide";
import ChatDotSquare from "@iconify-icons/ep/chat-dot-square";
import ElementPlus from "@iconify-icons/ep/element-plus";
import Memo from "@iconify-icons/ep/memo";

addIcon("check", Check);
addIcon("home-filled", HomeFilled);
addIcon("lollipop", Lollipop);
addIcon("refresh-right", RefreshRight);
addIcon("close", Close);
addIcon("close-bold", CloseBold);
addIcon("bell", Bell);
addIcon("search", Search);
addIcon("refresh", Refresh);
addIcon("info-filled", InfoFilled);
addIcon("collection", Collection);
addIcon("download", Download);
addIcon("trend-charts", TrendCharts);
addIcon("position", Position);
addIcon("map-location", MapLocation);
addIcon("location", Location);
addIcon("iphone", Iphone);
addIcon("tickets", Tickets);
addIcon("postcard", Postcard);
addIcon("female", Female);
addIcon("connection", Connection);
addIcon("calendar", Calendar);
addIcon("medal", Medal);
addIcon("link", Link);
addIcon("house", House);
addIcon("user-em", UserEM);
addIcon("present", Present);
addIcon("warning", Warning);
addIcon("delete", Delete);
addIcon("download", DownLoad);
addIcon("upload", Upload);
addIcon("edit-pen", EditPen);
addIcon("data-analysis", DataAnalysis);
addIcon("money", Money);
addIcon("coin", Coin);
addIcon("operation", Operation);
addIcon("office-building", OfficeBuilding);
addIcon("lock", Lock);
addIcon("credit-card", CreditCard);
addIcon("guide", Guide);
addIcon("chat-dot-square", ChatDotSquare);
addIcon("element-plus", ElementPlus);
addIcon("memo", Memo);
